apiVersion: v1
kind: ConfigMap
metadata:
  name: routr
  namespace: voip
data:
  log4j2.yml: |-
    Configuration:
      Appenders:
        Console:
          PatternLayout:
            pattern: '[%-5level] %msg%n'
          name: Console
          target: SYSTEM_OUT
        # Do not remove this appender as is needed by the /system/logs endpoint
        # If you want to save the logs elsewhere just add another appender.
        RollingFile:
          - name: LogToRollingFile
            fileName: "${sys:ROUTR_DATA}/logs/routr.log"
            filePattern: "${sys:ROUTR_DATA}/logs/$${date:yyyy-MM}/routr-%d{MM-dd-yyyy}-%i.log.gz"
            PatternLayout:
              pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
            Policies:
              SizeBasedTriggeringPolicy:
                size: 10MB
            DefaultRollOverStrategy:
              max: 10
      Loggers:
        Root:
          level: debug
          AppenderRef:
          - ref: Console
          - ref: LogToRollingFile
---
apiVersion: v1
kind: Service
metadata:
  name: routr-sip
  namespace: voip
  labels:
    app: routr
spec:
  type: NodePort
  # "Local" preserves the client source IP and avoids a second hop for
  # LoadBalancer and NodePort
  externalTrafficPolicy: Local
  ports:
  - name: sip
    port: 5060
  selector:
    app: routr
    tier: sip
---
apiVersion: v1
kind: Service
metadata:
  name: routr-rest
  namespace: voip
  labels:
    app: routr
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4567
  selector:
    app: routr
    tier: sip
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: routr-rest
  namespace: voip
spec:
  ingressClassName: traefik
  rules:
  - host: routr-rest.tahiro.org
    http:
      paths:
      - backend:
          service:
            name: routr-rest
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routr
  namespace: voip
  labels:
    app: routr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: routr
  template:
    metadata:
      labels:
        app: routr
        tier: sip
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: routr
        image: fonoster/routr:latest
        env:
        - name: DATA_SOURCE_PROVIDER
          value: redis_data_provider
        - name: DATA_SOURCE_PARAMETERS
          value: host=redis-routr,port=6379
        - name: REGISTRAR_INTF
          value: Internal
        - name: REST_SERVICE_UNSECURED
          value: 'true'
        ports:
        - containerPort: 5060
          name: sip
        - containerPort: 4567
          name: http
        volumeMounts:
        - name: routr-config
          mountPath: /opt/routr/config/log4j2.yml
          subPath: log4j2.yml
      volumes:
      - name: routr-config
        configMap:
          name: routr
